## Using NumPy to perform arithmetic operations on data

In [1]:
import numpy as np
from numpy.random import randn

In [2]:
np.set_printoptions(precision=2)

## Creating arrays
### Creating arrays using a list

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b = np.array([[10,20,30],[40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

### Creating arrays via assignment

In [5]:
np.random.seed(25)
c = 36*np.random.rand(6)
c

array([31.32, 20.96, 10.04,  6.69, 14.8 ,  4.23])

In [7]:
d=np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [8]:
a*10

array([10, 20, 30, 40, 50, 60])

In [9]:
c+a

array([32.32, 22.96, 13.04, 10.69, 19.8 , 10.23])

In [10]:
c-a

array([30.32, 18.96,  7.04,  2.69,  9.8 , -1.77])

In [11]:
c*a

array([31.32, 41.92, 30.11, 26.77, 74.  , 25.35])

In [12]:
c/a

array([31.32, 10.48,  3.35,  1.67,  2.96,  0.7 ])

### Multiplying matrices and basic linear algebra